services:
  - type: web
    name: app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-db
          property: connectionString
    migrations:
      run: true
